name: Issue Event Details

on:
  issues:
    types: [opened, edited, reopened, closed]

jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print issue details
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Action: ${{ github.event.action }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue Author: ${{ github.event.issue.user.login }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
